#!/bin/bash
set -eux

. "$(dirname "$(readlink -f "$0")")"/functions.sh

# Puppet manifests
CONCAT_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-concat-1.2.4.tar.gz"
STDLIB_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-stdlib-4.7.0.tar.gz"
ELASTICSEARCH_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/elasticsearch-elasticsearch-0.10.1.tar.gz"
# Dependency for Elasticsearch 0.10.x
DATACAT_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/richardc-datacat-0.6.2.tar.gz"
FIREWALL_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-firewall-1.7.2.tar.gz"
APACHE_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-apache-1.4.0.tar.gz"
HTPASSWD_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/leinaddm-htpasswd-0.0.3.tar.gz"

TZ_VERSION="2016j-0ubuntu0.14.04_all"

# Packages needed to install JRE headless
download_packages http://mirrors.kernel.org/ubuntu/pool/main/p/pcsc-lite/libpcsclite1_1.8.10-1ubuntu1_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/j/java-common/java-common_0.51_all.deb \
    "http://security.ubuntu.com/ubuntu/pool/main/t/tzdata/tzdata-java_${TZ_VERSION}.deb" \
    "http://security.ubuntu.com/ubuntu/pool/main/t/tzdata/tzdata_${TZ_VERSION}.deb" \
    http://security.ubuntu.com/ubuntu/pool/main/c/ca-certificates/ca-certificates_20160104ubuntu0.14.04.1_all.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/c/ca-certificates-java/ca-certificates-java_20130815ubuntu1_all.deb \
    http://security.ubuntu.com/ubuntu/pool/main/o/openjdk-7/openjdk-7-jre-headless_7u121-2.6.8-1ubuntu0.14.04.3_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/c/ca-certificates-java/ca-certificates-java_20130815ubuntu1_all.deb \
    https://download.elastic.co/kibana/kibana/kibana_4.5.1_amd64.deb \
    https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.3/elasticsearch-2.3.3.deb

# Download curator and dependencies
download_packages http://packages.elastic.co/curator/4/debian/pool/main/p/python/python-elasticsearch-curator_4.0.6_all.deb \
    http://packages.elastic.co/curator/4/debian/pool/main/p/python/python-elasticsearch_2.3.0_all.deb \
    http://packages.elastic.co/curator/4/debian/pool/main/p/python/python-click_6.6_all.deb \
    http://packages.elastic.co/curator/4/debian/pool/main/p/python/python-pyyaml_3.11_amd64.deb
check_md5sum python-elasticsearch-curator_4.0.6_all.deb eb69388edf54aafa2445423f615c0817
check_md5sum python-click_6.6_all.deb f508745fcd6f64a317cc94603b7f4f9d
check_md5sum python-pyyaml_3.11_amd64.deb 9f4ef75d24f6bc92879e0c57dc4f4b71
check_md5sum python-elasticsearch_2.3.0_all.deb 4d17c82d397fc57034d78e9d09ae400d

# Install puppet manifests
download_puppet_module "concat" "$CONCAT_TARBALL_URL"
download_puppet_module "stdlib" "$STDLIB_TARBALL_URL"
download_puppet_module "elasticsearch" "$ELASTICSEARCH_TARBALL_URL"
download_puppet_module "firewall" "$FIREWALL_TARBALL_URL"
download_puppet_module "datacat" "$DATACAT_TARBALL_URL"
download_puppet_module "apache" "${APACHE_TARBALL_URL}"
download_puppet_module "htpasswd" "${HTPASSWD_TARBALL_URL}"

# Update tzdata-java package to remove strict dependency on tzdata (see LP bug #1560436)
ROOT="$(dirname "$(readlink -f "$0")")"
DEB_REPO="${ROOT}"/repositories/ubuntu/
TMP_DIR=$(mktemp -d || exit 1)
cp "${DEB_REPO}/tzdata-java_${TZ_VERSION}.deb" "${TMP_DIR}"
cd "${TMP_DIR}" || exit 1
ar x "tzdata-java_${TZ_VERSION}.deb" || exit 1
tar xzvf control.tar.gz || exit 1
sed -i 's/Depends: tzdata (=/Depends: tzdata (>=/' control || exit 1
tar czvf control.tar.gz md5sums control || exit 1
ar r "tzdata-java_${TZ_VERSION}.deb" control.tar.gz data.tar.xz || exit 1
mv "tzdata-java_${TZ_VERSION}.deb" "${DEB_REPO}/" || exit 1
cd /tmp || exit 1
rm -rf "${TMP_DIR}" || exit 1
