#!/bin/bash

NODES_LIST_FILE=/tmp/nodes

if [ ! -f "${NODES_LIST_FILE}" ]; then
  echo "You must run the following command on Fuel master node before:"
  echo "  fuel nodes > ${NODES_LIST_FILE}"
  echo "You should run this script by saving its output:"
  echo "  ${0} | tee /tmp/upgrade_0.8.0_to_0.8.1.log"
  exit 1

fi

# collectd processes could be wedge, stop or kill them
# see https://bugs.launchpad.net/lma-toolchain/+bug/1560946
echo "** Stopping Collectd"
for n in $(grep True $NODES_LIST_FILE|grep ready|awk -F '|' '{print $5}'); do
    echo $n;
    ssh $n '/etc/init.d/collectd  stop; pkill -9 collectd'
done

# Several hekad process may run on these nodes, stop or kill them
# see https://bugs.launchpad.net/lma-toolchain/+bug/1561109
echo "** Stopping Heka"
for n in $(grep -E 'osd|compute|cinder|elasticsearch|influxdb|alerting' $NODES_LIST_FILE|grep True|grep ready|awk -F '|' '{print $5}'); do
    echo $n;
    ssh $n 'service lma_collector stop; pkill -TERM hekad; sleep 5; pkill -9 hekad;'
done

# Stop heka on controllers during the upgrade to avoid losing logs and notification
# (because elasticsearch will be stopped and heka doesn't buffering data with 0.8.0)
echo "** Stopping Heka on controller(s)"
for n in $(grep controller $NODES_LIST_FILE|grep True|grep ready|awk -F '|' '{print $5}'|tail -n 1); do
    echo $n;
    ssh $n 'crm resource stop lma_collector'
done

# Upgrade Heka manually due to the issue with heka package versionning
# https://github.com/mozilla-services/heka/issues/1892
echo "** Upgrading Heka to 0.10.0"
for n in $(grep True $NODES_LIST_FILE|grep ready|awk -F '|' '{print $5}'); do
    echo $n;
    ssh $n 'apt-get update; apt-get install --force-yes -y heka; dpkg -l|grep heka'
done

# Elasticsearch needs to be stopped for following necessary operations
# see https://bugs.launchpad.net/lma-toolchain/+bug/1559126
echo "** Stopping Elasticsearch"
for n in $(grep -E 'elasticsearch' $NODES_LIST_FILE|grep True|grep ready|awk -F '|' '{print $5}'); do
    echo $n;
    ssh $n 'service elasticsearch-es-01 stop; ps aux|grep -v grep|grep java| grep elasticsearch && echo "** Elasticsearch is not stopped, you should try manually"'
done
